FoodiesVs/Foodies/Models/Ingredient.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Foodies.Models
{
    public class Ingredient
    {
        //https://stackoverflow.com/questions/10710393/nullable-property-to-entity-field-entity-framework-through-code-first/10710934
        // Code first nullable and requered
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public int EnergyKcal { get; set; }
        public int? EnergyKj { get; set; }
        public decimal? Water { get; set; }
        public decimal? EggWhite { get; set; }
        public decimal? Carbohydrates { get; set; }
        public decimal? Sugar { get; set; }
        public decimal? Fat { get; set; }
        [Display(Name = "Saturated Fat")]
        public decimal? SaturatedFat { get; set; }
        [Display(Name = " Single Saturated Fat")]
        public decimal? SingleSaturatedFat { get; set; }
        [Display(Name = "Multi Saturated Fat")]
        public decimal? MultiSaturatedFat { get; set; }
        public decimal? Cholesterol { get; set; }
        public decimal? Fiber { get; set; }

        public ICollection<MealIngredient> MealIngredients { get; set; }
    }
}

FoodiesVs/Foodies/ViewModels/IngredientViewModel.cs
using Foodies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.ViewModels
{
    public class IngredientViewModel
    {
        public Ingredient Ingredient { get; set; }
    }
}

FoodiesVs/Foodies/Controllers/API/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Foodies.Data;
using Foodies.Models;
using Foodies.Data.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace Foodies.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class IngredientController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;

        public IngredientController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: api/Ingredient
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Ingredient>>> GetIngredients()
        {
            return await _unitOfWork.IngredientRepository.GetAll().ToListAsync();
        }

        // GET: api/Ingredient/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Ingredient>> GetIngredient(int id)
        {
            Ingredient ingredient = await _unitOfWork.IngredientRepository.GetById(id);

            if (ingredient == null)
            {
                return NotFound();
            }

            return ingredient;
        }

        // PUT: api/Ingredient/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutIngredient(int id, Ingredient ingredient)
        {
            if (id != ingredient.IngredientId)
            {
                return BadRequest();
            }
            _unitOfWork.IngredientRepository.Update(ingredient);
            await _unitOfWork.Save();
            return NoContent();
        }

        // POST: api/Ingredient
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Ingredient>> PostIngredient(Ingredient ingredient)
        {
            _unitOfWork.IngredientRepository.Create(ingredient);
            await _unitOfWork.Save();

            return CreatedAtAction("GetIngredient", new { id = ingredient.IngredientId }, ingredient);
        }

        // DELETE: api/Ingredient/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Ingredient>> DeleteIngredient(int id)
        {
            Ingredient ingredient = await _unitOfWork.IngredientRepository.GetById(id);
            if (ingredient == null)
            {
                return NotFound();
            }

            _unitOfWork.IngredientRepository.Delete(ingredient);
            await _unitOfWork.Save();

            return NoContent();
        }

        private bool IngredientExists(int id)
        {
            if (_unitOfWork.IngredientRepository.GetById(id) != null)
            {
                return true;
            }
            return false;            
        }
    }
}

FoodiesVs/Foodies/Controllers/IngredientController.cs
using Foodies.Data;
using Foodies.Models;
using Foodies.Validators;
using Foodies.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class IngredientController : Controller
    {
        private readonly FoodiesContext _context;

        public IngredientController(FoodiesContext context)
        {
            _context = context;
        }

        // GET: Ingredient
        public async Task<IActionResult> Index()
        {
            IndexIngredientViewModel indexIngredientViewModel = new IndexIngredientViewModel();
            indexIngredientViewModel.Ingredients = await _context.Ingredients.ToListAsync();
            return View(indexIngredientViewModel);
        }

        //GET: Searchfilter

        public async Task<IActionResult> Search(IndexIngredientViewModel indexIngredientViewModel)
        {
            if (!string.IsNullOrEmpty(indexIngredientViewModel.IngredientSearch))
            {
                indexIngredientViewModel.Ingredients = await _context.Ingredients
                    .Where(c => c.Name.Contains(indexIngredientViewModel.IngredientSearch)).ToListAsync();
            }
            else
            {
                indexIngredientViewModel.Ingredients = await _context.Ingredients.ToListAsync();
            }
            return View("Index", indexIngredientViewModel);
        }

        // GET: Ingredient/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var ingredient = await _context.Ingredients
                .FirstOrDefaultAsync(m => m.IngredientId == id);
            if (ingredient == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(ingredient);
        }

        // GET: Ingredient/Create
        public IActionResult Create()
        {
            IngredientViewModel createIngredientViewModel = new IngredientViewModel();
            createIngredientViewModel.Ingredient = new Ingredient();
            return View(createIngredientViewModel);
        }

        // POST: Ingredient/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IngredientViewModel createIngredientViewModel)
        {
            var validator = new IngredientValidator(_context.Ingredients);
            var result = validator.Validate(createIngredientViewModel.Ingredient);
            if (result.IsValid)
            {
                _context.Add(createIngredientViewModel.Ingredient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.ErrorMessage);
                }
            }
            return View(createIngredientViewModel);
        }

        // GET: Ingredient/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var ingredient = await _context.Ingredients.FindAsync(id);
            if (ingredient == null)
            {
                return RedirectToAction("Error", "Home");
            }
            IngredientViewModel ingredientViewModel = new IngredientViewModel();
            ingredientViewModel.Ingredient = ingredient;
            return View(ingredientViewModel);
        }

        // POST: Ingredient/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IngredientViewModel editIngredientViewModel)
        {
            if (id != editIngredientViewModel.Ingredient.IngredientId)
            {
                return RedirectToAction("Error", "Home");
            }
            Ingredient checkIngredientName = await _context.Ingredients.SingleOrDefaultAsync(x => x.Name == editIngredientViewModel.Ingredient.Name && x.IngredientId == editIngredientViewModel.Ingredient.IngredientId);
            var result = new FluentValidation.Results.ValidationResult();//Bypass the name validator and didn't know how to do it any other way
            if (checkIngredientName != null)
            {
               var validator = new EditIngredientValidator();
               result = validator.Validate(editIngredientViewModel.Ingredient);
            }
            else
            {
               var validator = new IngredientValidator(_context.Ingredients);
               result = validator.Validate(editIngredientViewModel.Ingredient);
            }            
            if (result.IsValid)
            {
                Ingredient ingredient = await _context.Ingredients.SingleOrDefaultAsync(x => x.IngredientId == id);
                if (ingredient != null)
                {
                    ingredient.Name = editIngredientViewModel.Ingredient.Name;
                    ingredient.EnergyKcal = editIngredientViewModel.Ingredient.EnergyKcal;
                    ingredient.EnergyKj = editIngredientViewModel.Ingredient.EnergyKj;
                    ingredient.Water = editIngredientViewModel.Ingredient.Water;
                    ingredient.EggWhite = editIngredientViewModel.Ingredient.EggWhite;
                    ingredient.Carbohydrates = editIngredientViewModel.Ingredient.Carbohydrates;
                    ingredient.Sugar = editIngredientViewModel.Ingredient.Sugar;
                    ingredient.Fat = editIngredientViewModel.Ingredient.Fat;
                    ingredient.SaturatedFat = editIngredientViewModel.Ingredient.SaturatedFat;
                    ingredient.SingleSaturatedFat = editIngredientViewModel.Ingredient.SingleSaturatedFat;
                    ingredient.MultiSaturatedFat = editIngredientViewModel.Ingredient.MultiSaturatedFat;
                    ingredient.Cholesterol = editIngredientViewModel.Ingredient.Cholesterol;
                    ingredient.Fiber = editIngredientViewModel.Ingredient.Fiber;
                    _context.Update(ingredient);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Could not edit the ingredient. Try again later.");
                }                
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, item.ErrorMessage);
                }
            }
            return View(editIngredientViewModel);
        }

        // GET: Ingredient/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var ingredient = await _context.Ingredients
                .FirstOrDefaultAsync(m => m.IngredientId == id);
            if (ingredient == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(ingredient);
        }

        // POST: Ingredient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ingredient = await _context.Ingredients.FindAsync(id);
            _context.Ingredients.Remove(ingredient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IngredientExists(int id)
        {
            return _context.Ingredients.Any(e => e.IngredientId == id);
        }
    }
}

FoodiesVs/Foodies/Views/Ingredient/Create.cshtml
@model Foodies.ViewModels.IngredientViewModel

@{
    ViewData["Title"] = "Create";
}

<div id="headerMain" class="py-5 bg-image-full">
    <h1 class="text-center">Add An Ingredient</h1>
    <p class="text-center"><strong>Happy Creating</strong></p>
</div>
<div class="mt-5">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <p>*All values are derived from 100 grams</p>
                <div class="form-group">
                    <label asp-for="Ingredient.Name" class="control-label"></label>
                    <input asp-for="Ingredient.Name" class="form-control" />
                    <span asp-validation-for="Ingredient.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.EnergyKcal" class="control-label"></label>
                    <input asp-for="Ingredient.EnergyKcal" class="form-control" />
                    <span asp-validation-for="Ingredient.EnergyKcal" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.EnergyKj" class="control-label"></label>
                    <input asp-for="Ingredient.EnergyKj" class="form-control" />
                    <span asp-validation-for="Ingredient.EnergyKj" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Water" class="control-label"></label>
                    <input asp-for="Ingredient.Water" class="form-control" />
                    <span asp-validation-for="Ingredient.Water" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.EggWhite" class="control-label"></label>
                    <input asp-for="Ingredient.EggWhite" class="form-control" />
                    <span asp-validation-for="Ingredient.EggWhite" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Carbohydrates" class="control-label"></label>
                    <input asp-for="Ingredient.Carbohydrates" class="form-control" />
                    <span asp-validation-for="Ingredient.Carbohydrates" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Sugar" class="control-label"></label>
                    <input asp-for="Ingredient.Sugar" class="form-control" />
                    <span asp-validation-for="Ingredient.Sugar" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Fat" class="control-label"></label>
                    <input asp-for="Ingredient.Fat" class="form-control" />
                    <span asp-validation-for="Ingredient.Fat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.SaturatedFat" class="control-label"></label>
                    <input asp-for="Ingredient.SaturatedFat" class="form-control" />
                    <span asp-validation-for="Ingredient.SaturatedFat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.SingleSaturatedFat" class="control-label"></label>
                    <input asp-for="Ingredient.SingleSaturatedFat" class="form-control" />
                    <span asp-validation-for="Ingredient.SingleSaturatedFat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.MultiSaturatedFat" class="control-label"></label>
                    <input asp-for="Ingredient.MultiSaturatedFat" class="form-control" />
                    <span asp-validation-for="Ingredient.MultiSaturatedFat" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Cholesterol" class="control-label"></label>
                    <input asp-for="Ingredient.Cholesterol" class="form-control" />
                    <span asp-validation-for="Ingredient.Cholesterol" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ingredient.Fiber" class="control-label"></label>
                    <input asp-for="Ingredient.Fiber" class="form-control" />
                    <span asp-validation-for="Ingredient.Fiber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FoodiesVs/Foodies/Views/Ingredient/Delete.cshtml
@model Foodies.Models.Ingredient

@{
    ViewData["Title"] = "Delete";
}

<div id="headerMain" class="py-5 bg-image-full">
    <h1 class="text-center">Delete An Ingredient</h1>
    <p class="text-center"><strong>It will be missed</strong></p>
</div>
<div class="card col-6 mt-4">
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.EnergyKcal)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.EnergyKcal)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.EnergyKj)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.EnergyKj)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Water)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Water)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.EggWhite)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.EggWhite)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Carbohydrates)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Carbohydrates)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Sugar)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Sugar)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Fat)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Fat)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.SaturatedFat)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.SaturatedFat)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.SingleSaturatedFat)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.SingleSaturatedFat)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.MultiSaturatedFat)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.MultiSaturatedFat)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Cholesterol)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Cholesterol)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Fiber)
        </dt>
        <dd class="col-sm-3">
            @Html.DisplayFor(model => model.Fiber)
        </dd>
    </dl>
</div>
<form asp-action="Delete" class="mt-4">
    <input type="hidden" asp-for="IngredientId" />
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</form>

FoodiesVs/Foodies/Views/Ingredient/Edit.cshtml
@model Foodies.ViewModels.IngredientViewModel

@{
    ViewData["Title"] = "Edit";
}

<div id="headerMain" class="py-5 bg-image-full">
    <h1 class="text-center">Edit Ingredient</h1>
    <p class="text-center"><strong>Happy Editing</strong></p>
</div>
<div class="row mt-5">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Ingredient.IngredientId" />
            <div class="form-group">
                <label asp-for="Ingredient.Name" class="control-label"></label>
                <input asp-for="Ingredient.Name" class="form-control" />
                <span asp-validation-for="Ingredient.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.EnergyKcal" class="control-label"></label>
                <input asp-for="Ingredient.EnergyKcal" class="form-control" />
                <span asp-validation-for="Ingredient.EnergyKcal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.EnergyKj" class="control-label"></label>
                <input asp-for="Ingredient.EnergyKj" class="form-control" />
                <span asp-validation-for="Ingredient.EnergyKj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Water" class="control-label"></label>
                <input asp-for="Ingredient.Water" class="form-control" />
                <span asp-validation-for="Ingredient.Water" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.EggWhite" class="control-label"></label>
                <input asp-for="Ingredient.EggWhite" class="form-control" />
                <span asp-validation-for="Ingredient.EggWhite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Carbohydrates" class="control-label"></label>
                <input asp-for="Ingredient.Carbohydrates" class="form-control" />
                <span asp-validation-for="Ingredient.Carbohydrates" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Sugar" class="control-label"></label>
                <input asp-for="Ingredient.Sugar" class="form-control" />
                <span asp-validation-for="Ingredient.Sugar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Fat" class="control-label"></label>
                <input asp-for="Ingredient.Fat" class="form-control" />
                <span asp-validation-for="Ingredient.Fat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.SaturatedFat" class="control-label"></label>
                <input asp-for="Ingredient.SaturatedFat" class="form-control" />
                <span asp-validation-for="Ingredient.SaturatedFat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.SingleSaturatedFat" class="control-label"></label>
                <input asp-for="Ingredient.SingleSaturatedFat" class="form-control" />
                <span asp-validation-for="Ingredient.SingleSaturatedFat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.MultiSaturatedFat" class="control-label"></label>
                <input asp-for="Ingredient.MultiSaturatedFat" class="form-control" />
                <span asp-validation-for="Ingredient.MultiSaturatedFat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Cholesterol" class="control-label"></label>
                <input asp-for="Ingredient.Cholesterol" class="form-control" />
                <span asp-validation-for="Ingredient.Cholesterol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredient.Fiber" class="control-label"></label>
                <input asp-for="Ingredient.Fiber" class="form-control" />
                <span asp-validation-for="Ingredient.Fiber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodiesVs/Foodies/Views/Ingredient/Index.cshtml
@model Foodies.ViewModels.IndexIngredientViewModel

@{
    ViewData["Title"] = "Index";
}

<div id="headerMain" class="py-5 bg-image-full">
    <h1 class="text-center">Ingredients</h1>
</div>
<div class="card mt-5">
    <form asp-controller="Ingredient" asp-action="Search" method="get" class="mt-4 ml-2">
        <div class="form-actions no-color">
            <p>
                <a asp-action="Create" class="btn btn-primary">Create New Ingredient</a>
                Search a category:
                <input asp-for="IngredientSearch" />
                <input type="submit" value="Search" class="btn btn-primary" />
                <a asp-controller="Ingredient" asp-action="Index" class="btn btn-primary">Full List</a>
            </p>
        </div>
    </form>
    <table class="table mt-2">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].EnergyKcal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].EnergyKj)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Water)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].EggWhite)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Carbohydrates)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Sugar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Fat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].SaturatedFat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].SingleSaturatedFat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].MultiSaturatedFat)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Cholesterol)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ingredients[0].Fiber)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Ingredients)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EnergyKcal)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EnergyKj)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Water)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EggWhite)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Carbohydrates)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sugar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SaturatedFat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SingleSaturatedFat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MultiSaturatedFat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cholesterol)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fiber)
                    </td>
                    <td class="text-right">
                        <a asp-action="Edit" asp-route-id="@item.IngredientId" class="btn btn-primary">Edit</a>
                        <a asp-action="Delete" asp-route-id="@item.IngredientId" class="btn btn-primary">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>