FoodiesVs/Foodies/Controllers/MealController.cs
using Foodies.Areas.Identity.Data;
using Foodies.Data;
using Foodies.Models;
using Foodies.Validators;
using Foodies.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MealController : Controller
    {
        private readonly FoodiesContext _context;
        private UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment webHostEnvironment;

        //https://www.c-sharpcorner.com/article/upload-and-display-image-in-asp-net-core-3-1/
        public MealController(FoodiesContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Meal
        public async Task<IActionResult> Index()
        {
            var foodiesContext = _context.Meals.Include(m => m.LevelPreperation).Include(m => m.PreperationTime);
            return View(await foodiesContext.ToListAsync());
        }

        // GET: Meal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var meal = await _context.Meals
                .Include(m => m.LevelPreperation)
                .Include(m => m.PreperationTime)
                .FirstOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(meal);
        }

        // GET: Meal/Create
        public IActionResult Create()
        {
            CreateMealViewModel model = new CreateMealViewModel();
            model.Meal = new Meal();
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level");
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes");
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = new List<int>();
            return View(model);
        }

        // POST: Meal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateMealViewModel model)
        {
            var userId = _userManager.GetUserId(User);
            EndUser endUser = await _context.EndUsers.FirstOrDefaultAsync(x => x.ApplicationUserId == userId);
            string uploadedFile = UploadedFile(model.MealImage);
            if (string.IsNullOrEmpty(uploadedFile))
            {
                ModelState.AddModelError(string.Empty, "Image is not selected");
            }
            if (endUser != null && ModelState.IsValid)
            {
                model.Meal.EndUserId = endUser.EndUserId;
                model.Meal.PictureMeal = uploadedFile;
                var validator = new MealValidator(_context.Meals);
                var result = validator.Validate(model.Meal);
                if (result.IsValid)
                {
                    if (model.SelectedCategories != null)
                    {
                        List<MealCategory> newCategories = new List<MealCategory>();
                        foreach (int CategoryId in model.SelectedCategories)
                        {
                            newCategories.Add(new MealCategory
                            {
                                MealId = model.Meal.MealId,
                                CategoryId = CategoryId
                            });
                        }
                        _context.Add(model.Meal);
                        await _context.SaveChangesAsync();
                        Meal meal = await _context.Meals
                            .Include(mc => mc.MealCategories)
                            .SingleOrDefaultAsync(meal => meal.MealId == model.Meal.MealId);
                        meal.MealCategories.AddRange(newCategories);
                        _context.Update(meal);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));

                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Select at least one category!");
                    }
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, item.ErrorMessage);
                    }
                }
            }
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level", model.Meal.LevelPreperationId);
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes", model.Meal.PreperationTimeId);
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = new List<int>();
            return View(model);
        }
        private string UploadedFile(IFormFile formFile)
        {
            string uniqueFileName = null;

            if (formFile != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "assets");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + formFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    formFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Meal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Meal meal = await _context.Meals.Include(c => c.MealCategories).SingleOrDefaultAsync(x => x.MealId == id);
            if (meal == null)
            {
                return RedirectToAction("Error", "Home");
            }
            EditMealViewModel model = new EditMealViewModel();
            model.Meal = meal;
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level", model.Meal.LevelPreperationId);
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes", model.Meal.PreperationTimeId);
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = meal.MealCategories.Select(mc => mc.CategoryId); 
            return View(model);
        }

        // POST: Meal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditMealViewModel model)
        {
            if (id != model.Meal.MealId)
            {
                return RedirectToAction("Error", "Home");
            }
            Meal meal = await _context.Meals.Include(c => c.MealCategories).SingleOrDefaultAsync(x => x.MealId == id);
            if (meal != null)
            {
                meal.Name = model.Meal.Name;
                meal.ShortDiscription = model.Meal.ShortDiscription;
                meal.PreperationDiscribtion = model.Meal.PreperationDiscribtion;
                meal.NumberOfPeople = model.Meal.NumberOfPeople;
                if (meal.PictureMeal != model.Meal.PictureMeal)
                {
                    meal.PictureMeal = UploadedFile(model.MealImage);
                }
                Meal checkMealName = await _context.Meals.SingleOrDefaultAsync(x => x.Name == model.Meal.Name && x.MealId == model.Meal.MealId);
                var result = new FluentValidation.Results.ValidationResult();//Bypass the name validator and didn't know how to do it any other way
                if (checkMealName != null)
                {
                    var validator = new EditMealValidator();
                    result = validator.Validate(model.Meal);
                }
                else
                {
                    var validator = new MealValidator(_context.Meals);
                    result = validator.Validate(model.Meal);
                }                
                if (result.IsValid)
                {
                    if (model.SelectedCategories != null)
                    {
                        List<MealCategory> newCategories = new List<MealCategory>();
                        foreach (int CategoryId in model.SelectedCategories)
                        {
                            newCategories.Add(new MealCategory
                            {
                                MealId = model.Meal.MealId,
                                CategoryId = CategoryId
                            });
                        }
                        meal.MealCategories.RemoveAll(mc => !newCategories.Contains(mc));
                        meal.MealCategories.AddRange(newCategories.Where(nc => !meal.MealCategories.Contains(nc)));

FoodiesVs/Foodies/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Foodies.Data;
using Foodies.Models;
using Microsoft.AspNetCore.Authorization;

namespace Foodies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UnitController : Controller
    {
        private readonly FoodiesContext _context;

        public UnitController(FoodiesContext context)
        {
            _context = context;
        }

        // GET: Unit
        public async Task<IActionResult> Index()
        {
            return View(await _context.Units.ToListAsync());
        }

        // GET: Unit/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var unit = await _context.Units
                .FirstOrDefaultAsync(m => m.UnitId == id);
            if (unit == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(unit);
        }

        // GET: Unit/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Unit/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UnitId,Name")] Unit unit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(unit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        // GET: Unit/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var unit = await _context.Units.FindAsync(id);
            if (unit == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(unit);
        }

        // POST: Unit/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UnitId,Name")] Unit unit)
        {
            if (id != unit.UnitId)
            {
                return RedirectToAction("Error", "Home");
            }

            if (ModelState.IsValid)
            {
                _context.Update(unit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(unit);
        }

        // GET: Unit/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var unit = await _context.Units
                .FirstOrDefaultAsync(m => m.UnitId == id);
            if (unit == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(unit);
        }

        // POST: Unit/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var unit = await _context.Units.FindAsync(id);
            _context.Units.Remove(unit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UnitExists(int id)
        {
            return _context.Units.Any(e => e.UnitId == id);
        }
    }
}

FoodiesVs/Foodies/Views/Shared/_AdminMenu.cshtml
@if (this.User.IsInRole("Admin") && this.User.Identity.IsAuthenticated)
{
    <!--https://bootstrapious.com/p/bootstrap-sidebar-->
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/assets/foodies logo.png" alt="Foodies Logo" class="logo"/>
                </a>
            </div>
            <div>
                <a asp-area="Identity" asp-page="/Account/Manage/Index">
                    <img src="~/assets/blank-profile-picture-973460_640.png" alt="avatar" class="avatar">
                </a>
                <p class="text-center">Logged in</p>
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a href="#mealSubMenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Meals</a>
                    <ul class="collapse list-unstyled" id="mealSubMenu">
                        <li>
                            <a asp-controller="Meal" asp-action="Index">Meal List</a>
                        </li>
                        <li>
                            <a asp-controller="Category" asp-action="Index">Category List</a>
                        </li>
                        <li>
                            <a asp-controller="Ingredient" asp-action="Index">Ingrediënt List</a>
                        </li>
                        <li>
                            <a asp-controller="LevelPreperation" asp-action="Index">Preperation Level List</a>
                        </li>
                        <li>
                            <a asp-controller="PreperationTime" asp-action="Index">Preperation Time List</a>
                        </li>
                        <li>
                            <a asp-controller="Unit" asp-action="Index">Measurement Unit List</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="Browse">Browse</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="Foodies">All about Foodies</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="TermsOfService">Terms of Service</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </nav>
    </div>
}

FoodiesVs/Foodies/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Foodies.Models
@using Foodies.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/headerMainPage.css" />
    <link rel="stylesheet" href="~/css/sideMenu.css" />
    <link rel="stylesheet" href="~/css/custom.css"/>
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/favicon.ico" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2 p-0">
                @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                {
                    <partial name="_AdminMenu" />
                }
                else
                {
                    <partial name="_UserMenu" />
                }
            </div>
            <div role="main" class="col-10 p-0">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/scripts/togglenav.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FoodiesVs/Foodies/Views/Shared/_UserMenu.cshtml
@using Microsoft.AspNetCore.Identity
@using Foodies.Models
@using Foodies.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

    <!--https://bootstrapious.com/p/bootstrap-sidebar-->
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <a asp-controller="Home" asp-action="Index">
                    <img src="~/assets/foodies logo.png" alt="Foodies Logo" class="logo" />
                </a>
            </div>
            <div>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <a asp-area="Identity" asp-page="/Account/Manage/Index">
                        <img src="~/assets/blank-profile-picture-973460_640.png" alt="avatar" class="avatar" />
                    </a>
                    <p class="text-center">Logged in</p>
                }
                else
                {
                    <a asp-area="Identity" asp-page="/Account/Login">
                        <img src="~/assets/blank-profile-picture-973460_640.png" alt="avatar" class="avatar" />
                    </a>
                    <p class="text-center">Log In</p>
                }
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a asp-controller="EndUser" asp-action="Browse">Browse</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="Foodies">All about Foodies</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="TermsOfService">Terms of Service</a>
                </li>
                <li>
                    <a asp-controller="EndUser" asp-action="Privacy">Privacy</a>
                </li>
            </ul>
        </nav>
    </div>