FoodiesVs/Foodies/Models/EndUser.cs
using Foodies.Areas.Identity.Data;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Foodies.Models
{
    public class EndUser
    {
        public int EndUserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Avatar { get; set; }
        [ForeignKey("ApplicationUser")]
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; }
        public ICollection<UserShoppinglist> UserShoppinglists { get; set; }
        public ICollection<MealWeekScheduleUser> MealWeekScheduleUsers { get; set; }
        public ICollection<FavoriteMeal> FavoriteMeals { get; set; }
        public ICollection<Rating> Ratings { get; set; }
        public ICollection<Meal> Meals { get; set; }

    }
}

FoodiesVs/Foodies/ViewModels/BrowseViewModel.cs
using Foodies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.ViewModels
{
    public class BrowseViewModel
    {
        public string MealSearch { get; set; }
        public List<Meal> Meals { get; set; }
    }
}

FoodiesVs/Foodies/Controllers/EndUserController.cs
using Foodies.Data;
using Foodies.Models;
using Foodies.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.Controllers
{
    [Authorize]
    public class EndUserController : Controller
    {
        private readonly FoodiesContext _context;

        public EndUserController(FoodiesContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Browse()
        {
            BrowseViewModel browseViewModel = new BrowseViewModel();
            browseViewModel.Meals = await _context.Meals
                .Include(m => m.MealCategories)
                .Include(m =>m.MealIngredients)
                .ToListAsync();
            return View(browseViewModel);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Search(BrowseViewModel browseViewModel)
        {
            if (!string.IsNullOrEmpty(browseViewModel.MealSearch))
            {
                browseViewModel.Meals = await _context.Meals
                    .Include(m => m.MealCategories)
                    .Include(m => m.MealIngredients)
                    .Where(c => c.Name.Contains(browseViewModel.MealSearch)).ToListAsync();
            }
            else
            {
                browseViewModel.Meals = await _context.Meals
                    .Include(m => m.MealCategories)
                    .Include(m => m.MealIngredients)
                    .ToListAsync();
            }
            return View("Browse", browseViewModel);
        }
        [AllowAnonymous]
        public IActionResult Foodies()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult TermsOfService()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Privacy()
        {
            return View();
        }
        // GET: EndUser
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.EndUsers.ToListAsync());
        }

        // GET: EndUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var endUser = await _context.EndUsers
                .FirstOrDefaultAsync(m => m.EndUserId == id);
            if (endUser == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(endUser);
        }

        // GET: EndUser/Create
        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }

        // POST: EndUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EndUserId,Name,LastName,UserName,Email,PasswordHash,Avatar,ApplicationUserId")] EndUser endUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(endUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(endUser);
        }

        // GET: EndUser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var endUser = await _context.EndUsers.FindAsync(id);
            if (endUser == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(endUser);
        }

        // POST: EndUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EndUserId,Name,LastName,UserName,Email,PasswordHash,Avatar,ApplicationUserId")] EndUser endUser)
        {
            if (id != endUser.EndUserId)
            {
                return RedirectToAction("Error", "Home");
            }

            if (ModelState.IsValid)
            {
                _context.Update(endUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(endUser);
        }

        // GET: EndUser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var endUser = await _context.EndUsers
                .FirstOrDefaultAsync(m => m.EndUserId == id);
            if (endUser == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(endUser);
        }

        // POST: EndUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var endUser = await _context.EndUsers.FindAsync(id);
            _context.EndUsers.Remove(endUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EndUserExists(int id)
        {
            return _context.EndUsers.Any(e => e.EndUserId == id);
        }
    }
}

FoodiesVs/Foodies/Controllers/MealController.cs
using Foodies.Areas.Identity.Data;
using Foodies.Data;
using Foodies.Models;
using Foodies.Validators;
using Foodies.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Foodies.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MealController : Controller
    {
        private readonly FoodiesContext _context;
        private UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment webHostEnvironment;

        //https://www.c-sharpcorner.com/article/upload-and-display-image-in-asp-net-core-3-1/
        public MealController(FoodiesContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            webHostEnvironment = hostEnvironment;
        }

        // GET: Meal
        public async Task<IActionResult> Index()
        {
            var foodiesContext = _context.Meals.Include(m => m.LevelPreperation).Include(m => m.PreperationTime);
            return View(await foodiesContext.ToListAsync());
        }

        // GET: Meal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var meal = await _context.Meals
                .Include(m => m.LevelPreperation)
                .Include(m => m.PreperationTime)
                .FirstOrDefaultAsync(m => m.MealId == id);
            if (meal == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(meal);
        }

        // GET: Meal/Create
        public IActionResult Create()
        {
            CreateMealViewModel model = new CreateMealViewModel();
            model.Meal = new Meal();
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level");
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes");
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = new List<int>();
            return View(model);
        }

        // POST: Meal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateMealViewModel model)
        {
            var userId = _userManager.GetUserId(User);
            EndUser endUser = await _context.EndUsers.FirstOrDefaultAsync(x => x.ApplicationUserId == userId);
            string uploadedFile = UploadedFile(model.MealImage);
            if (string.IsNullOrEmpty(uploadedFile))
            {
                ModelState.AddModelError(string.Empty, "Image is not selected");
            }
            if (endUser != null && ModelState.IsValid)
            {
                model.Meal.EndUserId = endUser.EndUserId;
                model.Meal.PictureMeal = uploadedFile;
                var validator = new MealValidator(_context.Meals);
                var result = validator.Validate(model.Meal);
                if (result.IsValid)
                {
                    if (model.SelectedCategories != null)
                    {
                        List<MealCategory> newCategories = new List<MealCategory>();
                        foreach (int CategoryId in model.SelectedCategories)
                        {
                            newCategories.Add(new MealCategory
                            {
                                MealId = model.Meal.MealId,
                                CategoryId = CategoryId
                            });
                        }
                        _context.Add(model.Meal);
                        await _context.SaveChangesAsync();
                        Meal meal = await _context.Meals
                            .Include(mc => mc.MealCategories)
                            .SingleOrDefaultAsync(meal => meal.MealId == model.Meal.MealId);
                        meal.MealCategories.AddRange(newCategories);
                        _context.Update(meal);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));

                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Select at least one category!");
                    }
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, item.ErrorMessage);
                    }
                }
            }
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level", model.Meal.LevelPreperationId);
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes", model.Meal.PreperationTimeId);
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = new List<int>();
            return View(model);
        }
        private string UploadedFile(IFormFile formFile)
        {
            string uniqueFileName = null;

            if (formFile != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "assets");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + formFile.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    formFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Meal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Meal meal = await _context.Meals.Include(c => c.MealCategories).SingleOrDefaultAsync(x => x.MealId == id);
            if (meal == null)
            {
                return RedirectToAction("Error", "Home");
            }
            EditMealViewModel model = new EditMealViewModel();
            model.Meal = meal;
            model.LevelPreperations = new SelectList(_context.LevelPreperations, "LevelPreperationId", "Level", model.Meal.LevelPreperationId);
            model.PreperationTimes = new SelectList(_context.PreperationTimes, "PreperationTimeId", "RangeMinutes", model.Meal.PreperationTimeId);
            model.Category = new SelectList(_context.Categories, "CategoryId", "Name");
            model.SelectedCategories = meal.MealCategories.Select(mc => mc.CategoryId); 
            return View(model);
        }

        // POST: Meal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditMealViewModel model)
        {
            if (id != model.Meal.MealId)
            {
                return RedirectToAction("Error", "Home");
            }
            Meal meal = await _context.Meals.Include(c => c.MealCategories).SingleOrDefaultAsync(x => x.MealId == id);
            if (meal != null)
            {
                meal.Name = model.Meal.Name;
                meal.ShortDiscription = model.Meal.ShortDiscription;
                meal.PreperationDiscribtion = model.Meal.PreperationDiscribtion;
                meal.NumberOfPeople = model.Meal.NumberOfPeople;
                if (meal.PictureMeal != model.Meal.PictureMeal)
                {
                    meal.PictureMeal = UploadedFile(model.MealImage);
                }
                Meal checkMealName = await _context.Meals.SingleOrDefaultAsync(x => x.Name == model.Meal.Name && x.MealId == model.Meal.MealId);
                var result = new FluentValidation.Results.ValidationResult();//Bypass the name validator and didn't know how to do it any other way
                if (checkMealName != null)
                {
                    var validator = new EditMealValidator();
                    result = validator.Validate(model.Meal);
                }
                else
                {
                    var validator = new MealValidator(_context.Meals);
                    result = validator.Validate(model.Meal);
                }                
                if (result.IsValid)
                {
                    if (model.SelectedCategories != null)
                    {
                        List<MealCategory> newCategories = new List<MealCategory>();
                        foreach (int CategoryId in model.SelectedCategories)
                        {
                            newCategories.Add(new MealCategory
                            {
                                MealId = model.Meal.MealId,
                                CategoryId = CategoryId
                            });
                        }
                        meal.MealCategories.RemoveAll(mc => !newCategories.Contains(mc));
                        meal.MealCategories.AddRange(newCategories.Where(nc => !meal.MealCategories.Contains(nc)));

FoodiesVs/Foodies/Views/EndUser/Browse.cshtml
@model Foodies.ViewModels.BrowseViewModel

@{
    ViewData["Title"] = "Foodies";
}
<div class="text-center">
    <div id="headerMain" class=" py-5 bg-image-full">
        <h1 class="text-center">Let's Get Coocking</h1>
    </div>
</div>
<div class="mt-5">
    <form asp-controller="EndUser" asp-action="Search" method="get" class="mt-4 ml-2">
        <div class="form-actions no-color">
            <p>
                Search A Meal:
                <input asp-for="MealSearch" />
                <input type="submit" value="Search" class="btn btn-primary" />
                <a asp-controller="EndUser" asp-action="Browse" class="btn btn-primary">Full List</a>
            </p>
        </div>
    </form>
    <div class="row">
        @foreach (Meal meal in Model.Meals)
        {
            if (meal.MealIngredients.Count != 0)
            {
                <div class="col-sm-2">
                    <a asp-controller="Meal" asp-action="Recipe" asp-route-id="@meal.MealId">
                        <div>
                            <img src="~/assets/@meal.PictureMeal" asp-append-version="true" alt="@meal.Name" class="avatar3" />
                            <p class="text-center textAvatarMeal">@meal.Name</p>
                        </div>
                    </a>
                </div>
            }
        }
    </div>
</div>

FoodiesVs/Foodies/Views/EndUser/Foodies.cshtml
<div class="text-center">
    <div id="headerMain" class=" py-5 bg-image-full">
        <h1 class="text-center">All About Foodies</h1>
        <p class="text-center">Happy Reading</p>
    </div>
</div>
<div class="card mt-5">
    <h2 class="m-3 p-1 text-center">To eat healthy or not</h2>
    <div class="row m-3 p-1">
        <div class="col-4">
            <img src="~/assets/pictureLieven.jpg" alt="creator" class="avatar2">
        </div>
        <div class="col-8">
            <h3>Where it all started</h3>
            <p>
                This website is created because of an assignment from school. <br />
                We had to create a webside in .net core with a topic of choice. Because of corona was going on at the time, the producer of
                this website was getting fat.<br /> He needed a way to find and create healthy foods to eat. There is no better way than to create a
                website of their own where you can gather all the meals and how to coock them.
            </p>
        </div>
    </div>
</div>

FoodiesVs/Foodies/Views/EndUser/TermsOfService.cshtml
<div class="text-center">
    <div id="headerMain" class=" py-5 bg-image-full">
        <h1 class="text-center">Terms and service</h1>
        <p class="text-center">Happy Reading</p>
    </div>
</div>
<div class="card mt-5">
    <!--automatic generated Terms and conditions from https://app.termsfeed.com/ -->
    <h1>Terms and Conditions</h1>
    <p>Last updated: December 21, 2020</p>
    <p>Please read these terms and conditions carefully before using Our Service.</p>
    <h1>Interpretation and Definitions</h1>
        <h2>Interpretation</h2>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        <h2>Definitions</h2>
        <p>For the purposes of these Terms and Conditions:</p>
        <ul>
            <li>
                <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
            </li>
            <li>
                <p><strong>Country</strong> refers to: Belgium</p>
            </li>
            <li>
                <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Foodies.</p>
            </li>
            <li>
                <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            </li>
            <li>
                <p><strong>Service</strong> refers to the Website.</p>
            </li>
            <li>
                <p><strong>Terms and Conditions</strong> (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions agreement has been created with the help of the <a href="https://www.termsfeed.com/terms-conditions-generator/" target="_blank">Terms and Conditions Generator</a>.</p>
            </li>
            <li>
                <p><strong>Third-party Social Media Service</strong> means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.</p>
            </li>
            <li>
                <p><strong>Website</strong> refers to Foodies, accessible from <a href="https://www.foodies.com" rel="external nofollow noopener" target="_blank">https://www.foodies.com</a></p>
            </li>
            <li>
                <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </li>
        </ul>
        <h1>Acknowledgment</h1>
        <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
        <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these Terms and Conditions. These Terms and Conditions apply to all visitors, users and others who access or use the Service.</p>
        <p>By accessing or using the Service You agree to be bound by these Terms and Conditions. If You disagree with any part of these Terms and Conditions then You may not access the Service.</p>
        <p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
        <p>Your access to and use of the Service is also conditioned on Your acceptance of and compliance with the Privacy Policy of the Company. Our Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your personal information when You use the Application or the Website and tells You about Your privacy rights and how the law protects You. Please read Our Privacy Policy carefully before using Our Service.</p>
        <h1>Links to Other Websites</h1>
        <p>Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.</p>
        <p>The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.</p>
        <p>We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.</p>
        <h1>Termination</h1>
        <p>We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.</p>
        <p>Upon termination, Your right to use the Service will cease immediately.</p>
        <h1>Limitation of Liability</h1>
        <p>Notwithstanding any damages that You might incur, the entire liability of the Company and any of its suppliers under any provision of this Terms and Your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by You through the Service or 100 USD if You haven't purchased anything through the Service.</p>
        <p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Terms), even if the Company or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</p>
        <p>Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In these states, each party's liability will be limited to the greatest extent permitted by law.</p>
        <h1>"AS IS" and "AS AVAILABLE" Disclaimer</h1>
        <p>The Service is provided to You "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, the Company, on its own behalf and on behalf of its Affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, the Company provides no warranty or undertaking, and makes no representation of any kind that the Service will meet Your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
        <p>Without limiting the foregoing, neither the Company nor any of the company's provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of the Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</p>
        <p>Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to You. But in such a case the exclusions and limitations set forth in this section shall be applied to the greatest extent enforceable under applicable law.</p>
        <h1>Governing Law</h1>
        <p>The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws.</p>
        <h1>Disputes Resolution</h1>
        <p>If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company.</p>
        <h1>For European Union (EU) Users</h1>
        <p>If You are a European Union consumer, you will benefit from any mandatory provisions of the law of the country in which you are resident in.</p>
        <h1>United States Legal Compliance</h1>
        <p>You represent and warrant that (i) You are not located in a country that is subject to the United States government embargo, or that has been designated by the United States government as a "terrorist supporting" country, and (ii) You are not listed on any United States government list of prohibited or restricted parties.</p>
        <h1>Severability and Waiver</h1>
        <h2>Severability</h2>
        <p>If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</p>
        <h2>Waiver</h2>
        <p>Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Terms shall not effect a party's ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach.</p>
        <h1>Translation Interpretation</h1>
        <p>
            These Terms and Conditions may have been translated if We have made them available to You on our Service.
            You agree that the original English text shall prevail in the case of a dispute.
        </p>
        <h1>Changes to These Terms and Conditions</h1>
        <p>We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. If a revision is material We will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at Our sole discretion.</p>
        <p>By continuing to access or use Our Service after those revisions become effective, You agree to be bound by the revised terms. If You do not agree to the new terms, in whole or in part, please stop using the website and the Service.</p>
        <h1>Contact Us</h1>
        <p>If you have any questions about these Terms and Conditions, You can contact us:</p>
        <ul>
            <li>By email: r0236874@student.thomasmore.be</li>
        </ul>
</div>












</div>